#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="alamaat")]
public partial class alamaatDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertUser_Master(User_Master instance);
  partial void UpdateUser_Master(User_Master instance);
  partial void DeleteUser_Master(User_Master instance);
  partial void Insertalamaat_Order(alamaat_Order instance);
  partial void Updatealamaat_Order(alamaat_Order instance);
  partial void Deletealamaat_Order(alamaat_Order instance);
  partial void Insertalamaat_User(alamaat_User instance);
  partial void Updatealamaat_User(alamaat_User instance);
  partial void Deletealamaat_User(alamaat_User instance);
  partial void Insertproduct_category(product_category instance);
  partial void Updateproduct_category(product_category instance);
  partial void Deleteproduct_category(product_category instance);
  partial void InsertOrder_product(Order_product instance);
  partial void UpdateOrder_product(Order_product instance);
  partial void DeleteOrder_product(Order_product instance);
  partial void InsertFileMaster(FileMaster instance);
  partial void UpdateFileMaster(FileMaster instance);
  partial void DeleteFileMaster(FileMaster instance);
  partial void Insertalamaat_subscriber(alamaat_subscriber instance);
  partial void Updatealamaat_subscriber(alamaat_subscriber instance);
  partial void Deletealamaat_subscriber(alamaat_subscriber instance);
  partial void InsertProductThumb(ProductThumb instance);
  partial void UpdateProductThumb(ProductThumb instance);
  partial void DeleteProductThumb(ProductThumb instance);
  partial void Insertalamaat_product(alamaat_product instance);
  partial void Updatealamaat_product(alamaat_product instance);
  partial void Deletealamaat_product(alamaat_product instance);
  #endregion
	
	public alamaatDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["alamaatConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public alamaatDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public alamaatDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public alamaatDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public alamaatDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<User_Master> User_Masters
	{
		get
		{
			return this.GetTable<User_Master>();
		}
	}
	
	public System.Data.Linq.Table<alamaat_Order> alamaat_Orders
	{
		get
		{
			return this.GetTable<alamaat_Order>();
		}
	}
	
	public System.Data.Linq.Table<alamaat_User> alamaat_Users
	{
		get
		{
			return this.GetTable<alamaat_User>();
		}
	}
	
	public System.Data.Linq.Table<product_category> product_categories
	{
		get
		{
			return this.GetTable<product_category>();
		}
	}
	
	public System.Data.Linq.Table<Order_product> Order_products
	{
		get
		{
			return this.GetTable<Order_product>();
		}
	}
	
	public System.Data.Linq.Table<FileMaster> FileMasters
	{
		get
		{
			return this.GetTable<FileMaster>();
		}
	}
	
	public System.Data.Linq.Table<alamaat_subscriber> alamaat_subscribers
	{
		get
		{
			return this.GetTable<alamaat_subscriber>();
		}
	}
	
	public System.Data.Linq.Table<ProductThumb> ProductThumbs
	{
		get
		{
			return this.GetTable<ProductThumb>();
		}
	}
	
	public System.Data.Linq.Table<alamaat_product> alamaat_products
	{
		get
		{
			return this.GetTable<alamaat_product>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Master")]
public partial class User_Master : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _tilte;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntilteChanging(string value);
    partial void OntilteChanged();
    #endregion
	
	public User_Master()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tilte", DbType="NVarChar(100)")]
	public string tilte
	{
		get
		{
			return this._tilte;
		}
		set
		{
			if ((this._tilte != value))
			{
				this.OntilteChanging(value);
				this.SendPropertyChanging();
				this._tilte = value;
				this.SendPropertyChanged("tilte");
				this.OntilteChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alamaat_Orders")]
public partial class alamaat_Order : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _id;
	
	private string _order_number;
	
	private System.Nullable<decimal> _subtotal;
	
	private System.Nullable<decimal> _discount;
	
	private System.Nullable<decimal> _tax;
	
	private System.Nullable<decimal> _total;
	
	private string _orderstatus;
	
	private System.Nullable<System.DateTime> _created;
	
	private System.Nullable<System.DateTime> _lastmodified;
	
	private string _shipment;
	
	private System.Nullable<decimal> _shippingtotal;
	
	private string _lastedit;
	
	private string _shipfirstname;
	
	private string _shiplastname;
	
	private string _shipmiddlename;
	
	private string _shipcompanyname;
	
	private string _shipaddress;
	
	private string _shippostalcode;
	
	private string _shipcity;
	
	private string _shipcountry;
	
	private string _shipphone;
	
	private string _shipmobilephone;
	
	private string _shipfax;
	
	private string _billfirstname;
	
	private string _billlastname;
	
	private string _billmiddlename;
	
	private string _billcompanyname;
	
	private string _billemail;
	
	private string _billaddress;
	
	private string _billpostalcode;
	
	private string _billcity;
	
	private string _billcountry;
	
	private string _billphone;
	
	private string _billmobilephone;
	
	private string _billfax;
	
	private EntitySet<Order_product> _Order_products;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void Onorder_numberChanging(string value);
    partial void Onorder_numberChanged();
    partial void OnsubtotalChanging(System.Nullable<decimal> value);
    partial void OnsubtotalChanged();
    partial void OndiscountChanging(System.Nullable<decimal> value);
    partial void OndiscountChanged();
    partial void OntaxChanging(System.Nullable<decimal> value);
    partial void OntaxChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void OnorderstatusChanging(string value);
    partial void OnorderstatusChanged();
    partial void OncreatedChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedChanged();
    partial void OnlastmodifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnlastmodifiedChanged();
    partial void OnshipmentChanging(string value);
    partial void OnshipmentChanged();
    partial void OnshippingtotalChanging(System.Nullable<decimal> value);
    partial void OnshippingtotalChanged();
    partial void OnlasteditChanging(string value);
    partial void OnlasteditChanged();
    partial void OnshipfirstnameChanging(string value);
    partial void OnshipfirstnameChanged();
    partial void OnshiplastnameChanging(string value);
    partial void OnshiplastnameChanged();
    partial void OnshipmiddlenameChanging(string value);
    partial void OnshipmiddlenameChanged();
    partial void OnshipcompanynameChanging(string value);
    partial void OnshipcompanynameChanged();
    partial void OnshipaddressChanging(string value);
    partial void OnshipaddressChanged();
    partial void OnshippostalcodeChanging(string value);
    partial void OnshippostalcodeChanged();
    partial void OnshipcityChanging(string value);
    partial void OnshipcityChanged();
    partial void OnshipcountryChanging(string value);
    partial void OnshipcountryChanged();
    partial void OnshipphoneChanging(string value);
    partial void OnshipphoneChanged();
    partial void OnshipmobilephoneChanging(string value);
    partial void OnshipmobilephoneChanged();
    partial void OnshipfaxChanging(string value);
    partial void OnshipfaxChanged();
    partial void OnbillfirstnameChanging(string value);
    partial void OnbillfirstnameChanged();
    partial void OnbilllastnameChanging(string value);
    partial void OnbilllastnameChanged();
    partial void OnbillmiddlenameChanging(string value);
    partial void OnbillmiddlenameChanged();
    partial void OnbillcompanynameChanging(string value);
    partial void OnbillcompanynameChanged();
    partial void OnbillemailChanging(string value);
    partial void OnbillemailChanged();
    partial void OnbilladdressChanging(string value);
    partial void OnbilladdressChanged();
    partial void OnbillpostalcodeChanging(string value);
    partial void OnbillpostalcodeChanged();
    partial void OnbillcityChanging(string value);
    partial void OnbillcityChanged();
    partial void OnbillcountryChanging(string value);
    partial void OnbillcountryChanged();
    partial void OnbillphoneChanging(string value);
    partial void OnbillphoneChanged();
    partial void OnbillmobilephoneChanging(string value);
    partial void OnbillmobilephoneChanged();
    partial void OnbillfaxChanging(string value);
    partial void OnbillfaxChanged();
    #endregion
	
	public alamaat_Order()
	{
		this._Order_products = new EntitySet<Order_product>(new Action<Order_product>(this.attach_Order_products), new Action<Order_product>(this.detach_Order_products));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_number", DbType="NVarChar(100)")]
	public string order_number
	{
		get
		{
			return this._order_number;
		}
		set
		{
			if ((this._order_number != value))
			{
				this.Onorder_numberChanging(value);
				this.SendPropertyChanging();
				this._order_number = value;
				this.SendPropertyChanged("order_number");
				this.Onorder_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> subtotal
	{
		get
		{
			return this._subtotal;
		}
		set
		{
			if ((this._subtotal != value))
			{
				this.OnsubtotalChanging(value);
				this.SendPropertyChanging();
				this._subtotal = value;
				this.SendPropertyChanged("subtotal");
				this.OnsubtotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> discount
	{
		get
		{
			return this._discount;
		}
		set
		{
			if ((this._discount != value))
			{
				this.OndiscountChanging(value);
				this.SendPropertyChanging();
				this._discount = value;
				this.SendPropertyChanged("discount");
				this.OndiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tax", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> tax
	{
		get
		{
			return this._tax;
		}
		set
		{
			if ((this._tax != value))
			{
				this.OntaxChanging(value);
				this.SendPropertyChanging();
				this._tax = value;
				this.SendPropertyChanged("tax");
				this.OntaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> total
	{
		get
		{
			return this._total;
		}
		set
		{
			if ((this._total != value))
			{
				this.OntotalChanging(value);
				this.SendPropertyChanging();
				this._total = value;
				this.SendPropertyChanged("total");
				this.OntotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderstatus", DbType="NVarChar(100)")]
	public string orderstatus
	{
		get
		{
			return this._orderstatus;
		}
		set
		{
			if ((this._orderstatus != value))
			{
				this.OnorderstatusChanging(value);
				this.SendPropertyChanging();
				this._orderstatus = value;
				this.SendPropertyChanged("orderstatus");
				this.OnorderstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime")]
	public System.Nullable<System.DateTime> created
	{
		get
		{
			return this._created;
		}
		set
		{
			if ((this._created != value))
			{
				this.OncreatedChanging(value);
				this.SendPropertyChanging();
				this._created = value;
				this.SendPropertyChanged("created");
				this.OncreatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodified", DbType="DateTime")]
	public System.Nullable<System.DateTime> lastmodified
	{
		get
		{
			return this._lastmodified;
		}
		set
		{
			if ((this._lastmodified != value))
			{
				this.OnlastmodifiedChanging(value);
				this.SendPropertyChanging();
				this._lastmodified = value;
				this.SendPropertyChanged("lastmodified");
				this.OnlastmodifiedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipment", DbType="NVarChar(100)")]
	public string shipment
	{
		get
		{
			return this._shipment;
		}
		set
		{
			if ((this._shipment != value))
			{
				this.OnshipmentChanging(value);
				this.SendPropertyChanging();
				this._shipment = value;
				this.SendPropertyChanged("shipment");
				this.OnshipmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shippingtotal", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> shippingtotal
	{
		get
		{
			return this._shippingtotal;
		}
		set
		{
			if ((this._shippingtotal != value))
			{
				this.OnshippingtotalChanging(value);
				this.SendPropertyChanging();
				this._shippingtotal = value;
				this.SendPropertyChanged("shippingtotal");
				this.OnshippingtotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastedit", DbType="NVarChar(100)")]
	public string lastedit
	{
		get
		{
			return this._lastedit;
		}
		set
		{
			if ((this._lastedit != value))
			{
				this.OnlasteditChanging(value);
				this.SendPropertyChanging();
				this._lastedit = value;
				this.SendPropertyChanged("lastedit");
				this.OnlasteditChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipfirstname", DbType="NVarChar(100)")]
	public string shipfirstname
	{
		get
		{
			return this._shipfirstname;
		}
		set
		{
			if ((this._shipfirstname != value))
			{
				this.OnshipfirstnameChanging(value);
				this.SendPropertyChanging();
				this._shipfirstname = value;
				this.SendPropertyChanged("shipfirstname");
				this.OnshipfirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shiplastname", DbType="NVarChar(100)")]
	public string shiplastname
	{
		get
		{
			return this._shiplastname;
		}
		set
		{
			if ((this._shiplastname != value))
			{
				this.OnshiplastnameChanging(value);
				this.SendPropertyChanging();
				this._shiplastname = value;
				this.SendPropertyChanged("shiplastname");
				this.OnshiplastnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipmiddlename", DbType="NVarChar(100)")]
	public string shipmiddlename
	{
		get
		{
			return this._shipmiddlename;
		}
		set
		{
			if ((this._shipmiddlename != value))
			{
				this.OnshipmiddlenameChanging(value);
				this.SendPropertyChanging();
				this._shipmiddlename = value;
				this.SendPropertyChanged("shipmiddlename");
				this.OnshipmiddlenameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipcompanyname", DbType="NVarChar(100)")]
	public string shipcompanyname
	{
		get
		{
			return this._shipcompanyname;
		}
		set
		{
			if ((this._shipcompanyname != value))
			{
				this.OnshipcompanynameChanging(value);
				this.SendPropertyChanging();
				this._shipcompanyname = value;
				this.SendPropertyChanged("shipcompanyname");
				this.OnshipcompanynameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipaddress", DbType="NVarChar(MAX)")]
	public string shipaddress
	{
		get
		{
			return this._shipaddress;
		}
		set
		{
			if ((this._shipaddress != value))
			{
				this.OnshipaddressChanging(value);
				this.SendPropertyChanging();
				this._shipaddress = value;
				this.SendPropertyChanged("shipaddress");
				this.OnshipaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shippostalcode", DbType="NVarChar(100)")]
	public string shippostalcode
	{
		get
		{
			return this._shippostalcode;
		}
		set
		{
			if ((this._shippostalcode != value))
			{
				this.OnshippostalcodeChanging(value);
				this.SendPropertyChanging();
				this._shippostalcode = value;
				this.SendPropertyChanged("shippostalcode");
				this.OnshippostalcodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipcity", DbType="NVarChar(100)")]
	public string shipcity
	{
		get
		{
			return this._shipcity;
		}
		set
		{
			if ((this._shipcity != value))
			{
				this.OnshipcityChanging(value);
				this.SendPropertyChanging();
				this._shipcity = value;
				this.SendPropertyChanged("shipcity");
				this.OnshipcityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipcountry", DbType="NVarChar(100)")]
	public string shipcountry
	{
		get
		{
			return this._shipcountry;
		}
		set
		{
			if ((this._shipcountry != value))
			{
				this.OnshipcountryChanging(value);
				this.SendPropertyChanging();
				this._shipcountry = value;
				this.SendPropertyChanged("shipcountry");
				this.OnshipcountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipphone", DbType="NVarChar(100)")]
	public string shipphone
	{
		get
		{
			return this._shipphone;
		}
		set
		{
			if ((this._shipphone != value))
			{
				this.OnshipphoneChanging(value);
				this.SendPropertyChanging();
				this._shipphone = value;
				this.SendPropertyChanged("shipphone");
				this.OnshipphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipmobilephone", DbType="NVarChar(100)")]
	public string shipmobilephone
	{
		get
		{
			return this._shipmobilephone;
		}
		set
		{
			if ((this._shipmobilephone != value))
			{
				this.OnshipmobilephoneChanging(value);
				this.SendPropertyChanging();
				this._shipmobilephone = value;
				this.SendPropertyChanged("shipmobilephone");
				this.OnshipmobilephoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipfax", DbType="NVarChar(100)")]
	public string shipfax
	{
		get
		{
			return this._shipfax;
		}
		set
		{
			if ((this._shipfax != value))
			{
				this.OnshipfaxChanging(value);
				this.SendPropertyChanging();
				this._shipfax = value;
				this.SendPropertyChanged("shipfax");
				this.OnshipfaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billfirstname", DbType="NVarChar(100)")]
	public string billfirstname
	{
		get
		{
			return this._billfirstname;
		}
		set
		{
			if ((this._billfirstname != value))
			{
				this.OnbillfirstnameChanging(value);
				this.SendPropertyChanging();
				this._billfirstname = value;
				this.SendPropertyChanged("billfirstname");
				this.OnbillfirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billlastname", DbType="NVarChar(100)")]
	public string billlastname
	{
		get
		{
			return this._billlastname;
		}
		set
		{
			if ((this._billlastname != value))
			{
				this.OnbilllastnameChanging(value);
				this.SendPropertyChanging();
				this._billlastname = value;
				this.SendPropertyChanged("billlastname");
				this.OnbilllastnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billmiddlename", DbType="NVarChar(100)")]
	public string billmiddlename
	{
		get
		{
			return this._billmiddlename;
		}
		set
		{
			if ((this._billmiddlename != value))
			{
				this.OnbillmiddlenameChanging(value);
				this.SendPropertyChanging();
				this._billmiddlename = value;
				this.SendPropertyChanged("billmiddlename");
				this.OnbillmiddlenameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billcompanyname", DbType="NVarChar(100)")]
	public string billcompanyname
	{
		get
		{
			return this._billcompanyname;
		}
		set
		{
			if ((this._billcompanyname != value))
			{
				this.OnbillcompanynameChanging(value);
				this.SendPropertyChanging();
				this._billcompanyname = value;
				this.SendPropertyChanged("billcompanyname");
				this.OnbillcompanynameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billemail", DbType="NVarChar(100)")]
	public string billemail
	{
		get
		{
			return this._billemail;
		}
		set
		{
			if ((this._billemail != value))
			{
				this.OnbillemailChanging(value);
				this.SendPropertyChanging();
				this._billemail = value;
				this.SendPropertyChanged("billemail");
				this.OnbillemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billaddress", DbType="NVarChar(MAX)")]
	public string billaddress
	{
		get
		{
			return this._billaddress;
		}
		set
		{
			if ((this._billaddress != value))
			{
				this.OnbilladdressChanging(value);
				this.SendPropertyChanging();
				this._billaddress = value;
				this.SendPropertyChanged("billaddress");
				this.OnbilladdressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billpostalcode", DbType="NVarChar(100)")]
	public string billpostalcode
	{
		get
		{
			return this._billpostalcode;
		}
		set
		{
			if ((this._billpostalcode != value))
			{
				this.OnbillpostalcodeChanging(value);
				this.SendPropertyChanging();
				this._billpostalcode = value;
				this.SendPropertyChanged("billpostalcode");
				this.OnbillpostalcodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billcity", DbType="NVarChar(100)")]
	public string billcity
	{
		get
		{
			return this._billcity;
		}
		set
		{
			if ((this._billcity != value))
			{
				this.OnbillcityChanging(value);
				this.SendPropertyChanging();
				this._billcity = value;
				this.SendPropertyChanged("billcity");
				this.OnbillcityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billcountry", DbType="NVarChar(100)")]
	public string billcountry
	{
		get
		{
			return this._billcountry;
		}
		set
		{
			if ((this._billcountry != value))
			{
				this.OnbillcountryChanging(value);
				this.SendPropertyChanging();
				this._billcountry = value;
				this.SendPropertyChanged("billcountry");
				this.OnbillcountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billphone", DbType="NVarChar(100)")]
	public string billphone
	{
		get
		{
			return this._billphone;
		}
		set
		{
			if ((this._billphone != value))
			{
				this.OnbillphoneChanging(value);
				this.SendPropertyChanging();
				this._billphone = value;
				this.SendPropertyChanged("billphone");
				this.OnbillphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billmobilephone", DbType="NVarChar(100)")]
	public string billmobilephone
	{
		get
		{
			return this._billmobilephone;
		}
		set
		{
			if ((this._billmobilephone != value))
			{
				this.OnbillmobilephoneChanging(value);
				this.SendPropertyChanging();
				this._billmobilephone = value;
				this.SendPropertyChanged("billmobilephone");
				this.OnbillmobilephoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billfax", DbType="NVarChar(100)")]
	public string billfax
	{
		get
		{
			return this._billfax;
		}
		set
		{
			if ((this._billfax != value))
			{
				this.OnbillfaxChanging(value);
				this.SendPropertyChanging();
				this._billfax = value;
				this.SendPropertyChanged("billfax");
				this.OnbillfaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alamaat_Order_Order_product", Storage="_Order_products", ThisKey="id", OtherKey="order_id")]
	public EntitySet<Order_product> Order_products
	{
		get
		{
			return this._Order_products;
		}
		set
		{
			this._Order_products.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Order_products(Order_product entity)
	{
		this.SendPropertyChanging();
		entity.alamaat_Order = this;
	}
	
	private void detach_Order_products(Order_product entity)
	{
		this.SendPropertyChanging();
		entity.alamaat_Order = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alamaat_Users")]
public partial class alamaat_User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _id;
	
	private string _title;
	
	private string _firstname;
	
	private string _lastname;
	
	private string _middlename;
	
	private string _username;
	
	private string _email;
	
	private string _password;
	
	private string _usertype;
	
	private System.Nullable<bool> _block;
	
	private System.Nullable<bool> _active;
	
	private System.Nullable<System.DateTime> _registerDate;
	
	private System.Nullable<System.DateTime> _activation;
	
	private System.Nullable<System.DateTime> _lastmodified;
	
	private System.Nullable<System.DateTime> _lastlogin;
	
	private string _city;
	
	private string _province;
	
	private string _country;
	
	private string _postalcode;
	
	private string _address;
	
	private string _phone;
	
	private string _mobilephone;
	
	private string _companyname;
	
	private string _fax;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnmiddlenameChanging(string value);
    partial void OnmiddlenameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnusertypeChanging(string value);
    partial void OnusertypeChanged();
    partial void OnblockChanging(System.Nullable<bool> value);
    partial void OnblockChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void OnregisterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnregisterDateChanged();
    partial void OnactivationChanging(System.Nullable<System.DateTime> value);
    partial void OnactivationChanged();
    partial void OnlastmodifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnlastmodifiedChanged();
    partial void OnlastloginChanging(System.Nullable<System.DateTime> value);
    partial void OnlastloginChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnpostalcodeChanging(string value);
    partial void OnpostalcodeChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnmobilephoneChanging(string value);
    partial void OnmobilephoneChanged();
    partial void OncompanynameChanging(string value);
    partial void OncompanynameChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    #endregion
	
	public alamaat_User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(100)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(100)")]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this.OnfirstnameChanging(value);
				this.SendPropertyChanging();
				this._firstname = value;
				this.SendPropertyChanged("firstname");
				this.OnfirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(100)")]
	public string lastname
	{
		get
		{
			return this._lastname;
		}
		set
		{
			if ((this._lastname != value))
			{
				this.OnlastnameChanging(value);
				this.SendPropertyChanging();
				this._lastname = value;
				this.SendPropertyChanged("lastname");
				this.OnlastnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middlename", DbType="NVarChar(100)")]
	public string middlename
	{
		get
		{
			return this._middlename;
		}
		set
		{
			if ((this._middlename != value))
			{
				this.OnmiddlenameChanging(value);
				this.SendPropertyChanging();
				this._middlename = value;
				this.SendPropertyChanged("middlename");
				this.OnmiddlenameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(100)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="NVarChar(100)")]
	public string usertype
	{
		get
		{
			return this._usertype;
		}
		set
		{
			if ((this._usertype != value))
			{
				this.OnusertypeChanging(value);
				this.SendPropertyChanging();
				this._usertype = value;
				this.SendPropertyChanged("usertype");
				this.OnusertypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_block", DbType="Bit")]
	public System.Nullable<bool> block
	{
		get
		{
			return this._block;
		}
		set
		{
			if ((this._block != value))
			{
				this.OnblockChanging(value);
				this.SendPropertyChanging();
				this._block = value;
				this.SendPropertyChanged("block");
				this.OnblockChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
	public System.Nullable<bool> active
	{
		get
		{
			return this._active;
		}
		set
		{
			if ((this._active != value))
			{
				this.OnactiveChanging(value);
				this.SendPropertyChanging();
				this._active = value;
				this.SendPropertyChanged("active");
				this.OnactiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registerDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> registerDate
	{
		get
		{
			return this._registerDate;
		}
		set
		{
			if ((this._registerDate != value))
			{
				this.OnregisterDateChanging(value);
				this.SendPropertyChanging();
				this._registerDate = value;
				this.SendPropertyChanged("registerDate");
				this.OnregisterDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activation", DbType="DateTime")]
	public System.Nullable<System.DateTime> activation
	{
		get
		{
			return this._activation;
		}
		set
		{
			if ((this._activation != value))
			{
				this.OnactivationChanging(value);
				this.SendPropertyChanging();
				this._activation = value;
				this.SendPropertyChanged("activation");
				this.OnactivationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodified", DbType="DateTime")]
	public System.Nullable<System.DateTime> lastmodified
	{
		get
		{
			return this._lastmodified;
		}
		set
		{
			if ((this._lastmodified != value))
			{
				this.OnlastmodifiedChanging(value);
				this.SendPropertyChanging();
				this._lastmodified = value;
				this.SendPropertyChanged("lastmodified");
				this.OnlastmodifiedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastlogin", DbType="DateTime")]
	public System.Nullable<System.DateTime> lastlogin
	{
		get
		{
			return this._lastlogin;
		}
		set
		{
			if ((this._lastlogin != value))
			{
				this.OnlastloginChanging(value);
				this.SendPropertyChanging();
				this._lastlogin = value;
				this.SendPropertyChanged("lastlogin");
				this.OnlastloginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(100)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="NVarChar(100)")]
	public string province
	{
		get
		{
			return this._province;
		}
		set
		{
			if ((this._province != value))
			{
				this.OnprovinceChanging(value);
				this.SendPropertyChanging();
				this._province = value;
				this.SendPropertyChanged("province");
				this.OnprovinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(100)")]
	public string country
	{
		get
		{
			return this._country;
		}
		set
		{
			if ((this._country != value))
			{
				this.OncountryChanging(value);
				this.SendPropertyChanging();
				this._country = value;
				this.SendPropertyChanged("country");
				this.OncountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postalcode", DbType="NVarChar(100)")]
	public string postalcode
	{
		get
		{
			return this._postalcode;
		}
		set
		{
			if ((this._postalcode != value))
			{
				this.OnpostalcodeChanging(value);
				this.SendPropertyChanging();
				this._postalcode = value;
				this.SendPropertyChanged("postalcode");
				this.OnpostalcodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(100)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobilephone", DbType="NVarChar(100)")]
	public string mobilephone
	{
		get
		{
			return this._mobilephone;
		}
		set
		{
			if ((this._mobilephone != value))
			{
				this.OnmobilephoneChanging(value);
				this.SendPropertyChanging();
				this._mobilephone = value;
				this.SendPropertyChanged("mobilephone");
				this.OnmobilephoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyname", DbType="NVarChar(100)")]
	public string companyname
	{
		get
		{
			return this._companyname;
		}
		set
		{
			if ((this._companyname != value))
			{
				this.OncompanynameChanging(value);
				this.SendPropertyChanging();
				this._companyname = value;
				this.SendPropertyChanged("companyname");
				this.OncompanynameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="NVarChar(100)")]
	public string fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this.OnfaxChanging(value);
				this.SendPropertyChanging();
				this._fax = value;
				this.SendPropertyChanged("fax");
				this.OnfaxChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_category")]
public partial class product_category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _id;
	
	private string _name;
	
	private EntitySet<alamaat_product> _alamaat_products;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
	
	public product_category()
	{
		this._alamaat_products = new EntitySet<alamaat_product>(new Action<alamaat_product>(this.attach_alamaat_products), new Action<alamaat_product>(this.detach_alamaat_products));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_category_alamaat_product", Storage="_alamaat_products", ThisKey="id", OtherKey="category")]
	public EntitySet<alamaat_product> alamaat_products
	{
		get
		{
			return this._alamaat_products;
		}
		set
		{
			this._alamaat_products.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_alamaat_products(alamaat_product entity)
	{
		this.SendPropertyChanging();
		entity.product_category = this;
	}
	
	private void detach_alamaat_products(alamaat_product entity)
	{
		this.SendPropertyChanging();
		entity.product_category = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Order_products")]
public partial class Order_product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _id;
	
	private System.Nullable<System.Guid> _order_id;
	
	private string _name;
	
	private string _status;
	
	private System.Nullable<decimal> _price;
	
	private System.Nullable<int> _quantity;
	
	private System.Nullable<decimal> _discount;
	
	private System.Nullable<decimal> _total;
	
	private System.Nullable<int> _cartid;
	
	private System.Nullable<System.Guid> _product_id;
	
	private EntityRef<alamaat_Order> _alamaat_Order;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void Onorder_idChanging(System.Nullable<System.Guid> value);
    partial void Onorder_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void OndiscountChanging(System.Nullable<decimal> value);
    partial void OndiscountChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void OncartidChanging(System.Nullable<int> value);
    partial void OncartidChanged();
    partial void Onproduct_idChanging(System.Nullable<System.Guid> value);
    partial void Onproduct_idChanged();
    #endregion
	
	public Order_product()
	{
		this._alamaat_Order = default(EntityRef<alamaat_Order>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> order_id
	{
		get
		{
			return this._order_id;
		}
		set
		{
			if ((this._order_id != value))
			{
				if (this._alamaat_Order.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onorder_idChanging(value);
				this.SendPropertyChanging();
				this._order_id = value;
				this.SendPropertyChanged("order_id");
				this.Onorder_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(100)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
	public System.Nullable<int> quantity
	{
		get
		{
			return this._quantity;
		}
		set
		{
			if ((this._quantity != value))
			{
				this.OnquantityChanging(value);
				this.SendPropertyChanging();
				this._quantity = value;
				this.SendPropertyChanged("quantity");
				this.OnquantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> discount
	{
		get
		{
			return this._discount;
		}
		set
		{
			if ((this._discount != value))
			{
				this.OndiscountChanging(value);
				this.SendPropertyChanging();
				this._discount = value;
				this.SendPropertyChanged("discount");
				this.OndiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> total
	{
		get
		{
			return this._total;
		}
		set
		{
			if ((this._total != value))
			{
				this.OntotalChanging(value);
				this.SendPropertyChanging();
				this._total = value;
				this.SendPropertyChanged("total");
				this.OntotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cartid", DbType="Int")]
	public System.Nullable<int> cartid
	{
		get
		{
			return this._cartid;
		}
		set
		{
			if ((this._cartid != value))
			{
				this.OncartidChanging(value);
				this.SendPropertyChanging();
				this._cartid = value;
				this.SendPropertyChanged("cartid");
				this.OncartidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> product_id
	{
		get
		{
			return this._product_id;
		}
		set
		{
			if ((this._product_id != value))
			{
				this.Onproduct_idChanging(value);
				this.SendPropertyChanging();
				this._product_id = value;
				this.SendPropertyChanged("product_id");
				this.Onproduct_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alamaat_Order_Order_product", Storage="_alamaat_Order", ThisKey="order_id", OtherKey="id", IsForeignKey=true)]
	public alamaat_Order alamaat_Order
	{
		get
		{
			return this._alamaat_Order.Entity;
		}
		set
		{
			alamaat_Order previousValue = this._alamaat_Order.Entity;
			if (((previousValue != value) 
						|| (this._alamaat_Order.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._alamaat_Order.Entity = null;
					previousValue.Order_products.Remove(this);
				}
				this._alamaat_Order.Entity = value;
				if ((value != null))
				{
					value.Order_products.Add(this);
					this._order_id = value.id;
				}
				else
				{
					this._order_id = default(Nullable<System.Guid>);
				}
				this.SendPropertyChanged("alamaat_Order");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileMaster")]
public partial class FileMaster : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _id;
	
	private string _filename;
	
	private System.Data.Linq.Binary _filecontent;
	
	private string _type;
	
	private string _description;
	
	private string _value;
	
	private System.Nullable<System.DateTime> _created;
	
	private System.Nullable<bool> _active;
	
	private EntitySet<ProductThumb> _ProductThumbs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void OnfilecontentChanging(System.Data.Linq.Binary value);
    partial void OnfilecontentChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OncreatedChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    #endregion
	
	public FileMaster()
	{
		this._ProductThumbs = new EntitySet<ProductThumb>(new Action<ProductThumb>(this.attach_ProductThumbs), new Action<ProductThumb>(this.detach_ProductThumbs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(100)")]
	public string filename
	{
		get
		{
			return this._filename;
		}
		set
		{
			if ((this._filename != value))
			{
				this.OnfilenameChanging(value);
				this.SendPropertyChanging();
				this._filename = value;
				this.SendPropertyChanged("filename");
				this.OnfilenameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filecontent", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary filecontent
	{
		get
		{
			return this._filecontent;
		}
		set
		{
			if ((this._filecontent != value))
			{
				this.OnfilecontentChanging(value);
				this.SendPropertyChanging();
				this._filecontent = value;
				this.SendPropertyChanged("filecontent");
				this.OnfilecontentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(100)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(100)")]
	public string value
	{
		get
		{
			return this._value;
		}
		set
		{
			if ((this._value != value))
			{
				this.OnvalueChanging(value);
				this.SendPropertyChanging();
				this._value = value;
				this.SendPropertyChanged("value");
				this.OnvalueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime")]
	public System.Nullable<System.DateTime> created
	{
		get
		{
			return this._created;
		}
		set
		{
			if ((this._created != value))
			{
				this.OncreatedChanging(value);
				this.SendPropertyChanging();
				this._created = value;
				this.SendPropertyChanged("created");
				this.OncreatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
	public System.Nullable<bool> active
	{
		get
		{
			return this._active;
		}
		set
		{
			if ((this._active != value))
			{
				this.OnactiveChanging(value);
				this.SendPropertyChanging();
				this._active = value;
				this.SendPropertyChanged("active");
				this.OnactiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FileMaster_ProductThumb", Storage="_ProductThumbs", ThisKey="id", OtherKey="fileid")]
	public EntitySet<ProductThumb> ProductThumbs
	{
		get
		{
			return this._ProductThumbs;
		}
		set
		{
			this._ProductThumbs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ProductThumbs(ProductThumb entity)
	{
		this.SendPropertyChanging();
		entity.FileMaster = this;
	}
	
	private void detach_ProductThumbs(ProductThumb entity)
	{
		this.SendPropertyChanging();
		entity.FileMaster = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alamaat_subscriber")]
public partial class alamaat_subscriber : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _id;
	
	private string _email;
	
	private bool _active;
	
	private System.DateTime _created;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    partial void OncreatedChanging(System.DateTime value);
    partial void OncreatedChanged();
    #endregion
	
	public alamaat_subscriber()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit NOT NULL")]
	public bool active
	{
		get
		{
			return this._active;
		}
		set
		{
			if ((this._active != value))
			{
				this.OnactiveChanging(value);
				this.SendPropertyChanging();
				this._active = value;
				this.SendPropertyChanged("active");
				this.OnactiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime NOT NULL")]
	public System.DateTime created
	{
		get
		{
			return this._created;
		}
		set
		{
			if ((this._created != value))
			{
				this.OncreatedChanging(value);
				this.SendPropertyChanging();
				this._created = value;
				this.SendPropertyChanged("created");
				this.OncreatedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductThumb")]
public partial class ProductThumb : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _id;
	
	private System.Guid _fileid;
	
	private string _filename;
	
	private System.Data.Linq.Binary _filecontent;
	
	private string _type;
	
	private string _description;
	
	private string _value;
	
	private System.Nullable<System.DateTime> _created;
	
	private System.Nullable<bool> _active;
	
	private EntityRef<FileMaster> _FileMaster;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnfileidChanging(System.Guid value);
    partial void OnfileidChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void OnfilecontentChanging(System.Data.Linq.Binary value);
    partial void OnfilecontentChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OncreatedChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    #endregion
	
	public ProductThumb()
	{
		this._FileMaster = default(EntityRef<FileMaster>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileid", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid fileid
	{
		get
		{
			return this._fileid;
		}
		set
		{
			if ((this._fileid != value))
			{
				if (this._FileMaster.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnfileidChanging(value);
				this.SendPropertyChanging();
				this._fileid = value;
				this.SendPropertyChanged("fileid");
				this.OnfileidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(100)")]
	public string filename
	{
		get
		{
			return this._filename;
		}
		set
		{
			if ((this._filename != value))
			{
				this.OnfilenameChanging(value);
				this.SendPropertyChanging();
				this._filename = value;
				this.SendPropertyChanged("filename");
				this.OnfilenameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filecontent", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary filecontent
	{
		get
		{
			return this._filecontent;
		}
		set
		{
			if ((this._filecontent != value))
			{
				this.OnfilecontentChanging(value);
				this.SendPropertyChanging();
				this._filecontent = value;
				this.SendPropertyChanged("filecontent");
				this.OnfilecontentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(100)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(100)")]
	public string value
	{
		get
		{
			return this._value;
		}
		set
		{
			if ((this._value != value))
			{
				this.OnvalueChanging(value);
				this.SendPropertyChanging();
				this._value = value;
				this.SendPropertyChanged("value");
				this.OnvalueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime")]
	public System.Nullable<System.DateTime> created
	{
		get
		{
			return this._created;
		}
		set
		{
			if ((this._created != value))
			{
				this.OncreatedChanging(value);
				this.SendPropertyChanging();
				this._created = value;
				this.SendPropertyChanged("created");
				this.OncreatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
	public System.Nullable<bool> active
	{
		get
		{
			return this._active;
		}
		set
		{
			if ((this._active != value))
			{
				this.OnactiveChanging(value);
				this.SendPropertyChanging();
				this._active = value;
				this.SendPropertyChanged("active");
				this.OnactiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FileMaster_ProductThumb", Storage="_FileMaster", ThisKey="fileid", OtherKey="id", IsForeignKey=true)]
	public FileMaster FileMaster
	{
		get
		{
			return this._FileMaster.Entity;
		}
		set
		{
			FileMaster previousValue = this._FileMaster.Entity;
			if (((previousValue != value) 
						|| (this._FileMaster.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._FileMaster.Entity = null;
					previousValue.ProductThumbs.Remove(this);
				}
				this._FileMaster.Entity = value;
				if ((value != null))
				{
					value.ProductThumbs.Add(this);
					this._fileid = value.id;
				}
				else
				{
					this._fileid = default(System.Guid);
				}
				this.SendPropertyChanged("FileMaster");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alamaat_products")]
public partial class alamaat_product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _id;
	
	private string _productname;
	
	private System.Guid _category;
	
	private System.Nullable<decimal> _price;
	
	private string _details;
	
	private System.Nullable<int> _rating;
	
	private System.Nullable<System.DateTime> _created;
	
	private System.Nullable<System.DateTime> _lastmodified;
	
	private System.Nullable<System.Guid> _fileid;
	
	private System.Nullable<decimal> _originalprice;
	
	private System.Nullable<int> _discount;
	
	private EntityRef<product_category> _product_category;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnproductnameChanging(string value);
    partial void OnproductnameChanged();
    partial void OncategoryChanging(System.Guid value);
    partial void OncategoryChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OndetailsChanging(string value);
    partial void OndetailsChanged();
    partial void OnratingChanging(System.Nullable<int> value);
    partial void OnratingChanged();
    partial void OncreatedChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedChanged();
    partial void OnlastmodifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnlastmodifiedChanged();
    partial void OnfileidChanging(System.Nullable<System.Guid> value);
    partial void OnfileidChanged();
    partial void OnoriginalpriceChanging(System.Nullable<decimal> value);
    partial void OnoriginalpriceChanged();
    partial void OndiscountChanging(System.Nullable<int> value);
    partial void OndiscountChanged();
    #endregion
	
	public alamaat_product()
	{
		this._product_category = default(EntityRef<product_category>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string productname
	{
		get
		{
			return this._productname;
		}
		set
		{
			if ((this._productname != value))
			{
				this.OnproductnameChanging(value);
				this.SendPropertyChanging();
				this._productname = value;
				this.SendPropertyChanged("productname");
				this.OnproductnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid category
	{
		get
		{
			return this._category;
		}
		set
		{
			if ((this._category != value))
			{
				if (this._product_category.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OncategoryChanging(value);
				this.SendPropertyChanging();
				this._category = value;
				this.SendPropertyChanged("category");
				this.OncategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="NVarChar(MAX)")]
	public string details
	{
		get
		{
			return this._details;
		}
		set
		{
			if ((this._details != value))
			{
				this.OndetailsChanging(value);
				this.SendPropertyChanging();
				this._details = value;
				this.SendPropertyChanged("details");
				this.OndetailsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rating", DbType="Int")]
	public System.Nullable<int> rating
	{
		get
		{
			return this._rating;
		}
		set
		{
			if ((this._rating != value))
			{
				this.OnratingChanging(value);
				this.SendPropertyChanging();
				this._rating = value;
				this.SendPropertyChanged("rating");
				this.OnratingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime")]
	public System.Nullable<System.DateTime> created
	{
		get
		{
			return this._created;
		}
		set
		{
			if ((this._created != value))
			{
				this.OncreatedChanging(value);
				this.SendPropertyChanging();
				this._created = value;
				this.SendPropertyChanged("created");
				this.OncreatedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodified", DbType="DateTime")]
	public System.Nullable<System.DateTime> lastmodified
	{
		get
		{
			return this._lastmodified;
		}
		set
		{
			if ((this._lastmodified != value))
			{
				this.OnlastmodifiedChanging(value);
				this.SendPropertyChanging();
				this._lastmodified = value;
				this.SendPropertyChanged("lastmodified");
				this.OnlastmodifiedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileid", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> fileid
	{
		get
		{
			return this._fileid;
		}
		set
		{
			if ((this._fileid != value))
			{
				this.OnfileidChanging(value);
				this.SendPropertyChanging();
				this._fileid = value;
				this.SendPropertyChanged("fileid");
				this.OnfileidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_originalprice", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> originalprice
	{
		get
		{
			return this._originalprice;
		}
		set
		{
			if ((this._originalprice != value))
			{
				this.OnoriginalpriceChanging(value);
				this.SendPropertyChanging();
				this._originalprice = value;
				this.SendPropertyChanged("originalprice");
				this.OnoriginalpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="Int")]
	public System.Nullable<int> discount
	{
		get
		{
			return this._discount;
		}
		set
		{
			if ((this._discount != value))
			{
				this.OndiscountChanging(value);
				this.SendPropertyChanging();
				this._discount = value;
				this.SendPropertyChanged("discount");
				this.OndiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_category_alamaat_product", Storage="_product_category", ThisKey="category", OtherKey="id", IsForeignKey=true)]
	public product_category product_category
	{
		get
		{
			return this._product_category.Entity;
		}
		set
		{
			product_category previousValue = this._product_category.Entity;
			if (((previousValue != value) 
						|| (this._product_category.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._product_category.Entity = null;
					previousValue.alamaat_products.Remove(this);
				}
				this._product_category.Entity = value;
				if ((value != null))
				{
					value.alamaat_products.Add(this);
					this._category = value.id;
				}
				else
				{
					this._category = default(System.Guid);
				}
				this.SendPropertyChanged("product_category");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
